name: Deploy with Helm
on:
  push:
    tags:
    - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: yuriartemiev/webapp-stage:${{ github.ref_name }}
    
    - name: Setup kubeconfig
      run: echo '${{ secrets.KUBECONFIG_FILE }}' > kubeconfig
    
    - name: Setup Helm
      uses: azure/setup-helm@v1
    
    - name: Deploy
      run: |
        export KUBECONFIG=kubeconfig
        helm upgrade --install webapp-stage ./helm/webapp-stage --set image.tag=${{ github.ref_name }}
